/** DoesTheDogDie konu adı (küçük harf) → Türkçe etiket. parents-guide.ts içindeki temel listeyi tamamlar. */
export const EXTRA_TOPIC_LABELS_TR: Record<string, string> = {
  "a child's dear toy is destroyed": "Çocuğun sevdiği oyuncak yok ediliyor",
  "autism specific abuse": "Otizme yönelik istismar",
  "cpr is performed": "Suni solunum / kalp masajı (CPR)",
  "d.i.d. misrepresentation": "Dissosiyatif kimlik bozukluğu yanlış temsil ediliyor",
  "someone becomes unconscious": "Biri bilincini kaybediyor",
  "there's audio gore": "Sesli vahşet (sadece ses olarak)",
  "a baby is stillborn": "Ölü doğum",
  "a bug is killed": "Bir böcek öldürülüyor",
  "a building collapses": "Bina çöküyor",
  "a car crashes": "Araba kazası",
  "a car honks or tires screech": "Korna / lastik sesi",
  "a cat dies": "Bir kedi ölüyor",
  "a child gets lost": "Çocuk kayboluyor",
  "a disability is demonized": "Engellilik kötü gösteriliyor",
  "a disability is miraculously cured": "Engellilik mucizevi şekilde iyileşiyor",
  "a dragon dies": "Bir ejderha ölüyor",
  "a family member dies": "Bir aile üyesi ölüyor",
  "a horse dies": "Bir at ölüyor",
  "a male character is ridiculed for crying": "Erkek karakter ağladığı için alay ediliyor",
  "a mentally ill person is violent": "Ruhsal hastalığı olan biri şiddet uyguluyor",
  "a minority is misrepresented": "Bir azınlık yanlış temsil ediliyor",
  "a non-human character dies": "İnsan olmayan bir karakter ölüyor",
  "a person is hit by a car": "Biri araba çarpması sonucu yaralanıyor",
  "a personality disorder is demonized": "Kişilik bozukluğu kötü gösteriliyor",
  "a pet dies": "Bir evcil hayvan ölüyor",
  "a plane crashes": "Uçak düşüyor",
  "a priceless artifact is destroyed": "Paha biçilmez bir eser yok ediliyor",
  "a rape victim is not believed": "Tecavüz mağduruna inanılmıyor",
  "a teacher abuses a student": "Öğretmen öğrenciyi istismar ediyor",
  "a trans person is depicted predatorily": "Trans birey tehditkâr biçimde gösteriliyor",
  "a woman gets slapped": "Bir kadına tokat atılıyor",
  "an lgbt person dies": "Bir LGBT birey ölüyor",
  "an lgbt+ person is outed": "LGBT+ birey zorla ifşa ediliyor",
  "an animal attacks someone": "Bir hayvan birine saldırıyor",
  "an animal dies": "Bir hayvan ölüyor",
  "an animal is abandoned": "Bir hayvan terk ediliyor",
  "an animal is hit by a vehicle": "Bir hayvana araç çarpıyor",
  "an animal is sad": "Üzgün bir hayvan",
  "an infant is abducted": "Bebek kaçırılıyor",
  "animals are abused": "Hayvanlara kötü davranılıyor",
  "animals were harmed in the making": "Çekimlerde hayvanlar zarar görmüş",
  "autism is misrepresented": "Otizm yanlış temsil ediliyor",
  "diabetes is mocked or misrepresented": "Diyabetle alay ediliyor / yanlış temsil ediliyor",
  "electro-therapy is used": "Elektroşok tedavisi",
  "existentialism is debated": "Varoluşçuluk tartışılıyor",
  "family members argue": "Aile içi tartışma",
  "hands are damaged": "Eller zarar görüyor",
  "it's told from an abuser's point of view": "Hikâye istismarcının gözünden anlatılıyor",
  "mental illness is stigmatized or mocked": "Ruhsal hastalık damgalanıyor / alay ediliyor",
  "rabbits are harmed": "Tavşanlar zarar görüyor",
  "reality is unstable or unhinged": "Gerçeklik algısı bozuluyor",
  "religion is discussed": "Din tartışılıyor",
  "scars are shown or discussed": "Yara izleri gösteriliyor / konuşuluyor",
  "sexual assault on men is a joke": "Erkeklere yönelik cinsel saldırı şaka konusu yapılıyor",
  "someone defecates": "Biri tuvaletini yapıyor",
  "someone disabled played by able-bodied": "Engelli karakteri engelsiz oyuncu canlandırıyor",
  "someone dislocates something": "Çıkık / eklem yerinden çıkması",
  "someone fakes a disability": "Biri engelli numarası yapıyor",
  "someone falls down stairs": "Merdivenden düşme",
  "someone has a chronic illness": "Biri kronik hastalık yaşıyor",
  "someone has a heart attack": "Kalp krizi",
  "someone has a meltdown": "Duygusal çöküş",
  "someone has a seizure": "Nöbet geçirme",
  "someone has a stroke": "İnme (felç)",
  "someone has agoraphobia": "Agorafobi",
  "someone has amnesia or memory loss": "Hafıza kaybı",
  "someone has an abortion": "Kürtaj",
  "someone has an allergic reaction": "Alerjik reaksiyon",
  "someone has an eating disorder": "Yeme bozukluğu",
  "someone has dementia/alzheimer's": "Demans / Alzheimer",
  "someone is brainwashed or mind controlled": "Zihin kontrolü / beyin yıkama",
  "someone is called a \"good boy\" or \"good girl\"": "Biri “aferin oğlum/kızım” diye çağrılıyor",
  "someone is called a hypochondriac": "Biri hastalık hastası diye suçlanıyor",
  "someone is drugged": "Biri bilinçsizce uyuşturuluyor",
  "someone is eaten": "Biri yeniyor",
  "someone is executed": "İdam / infaz",
  "someone is hit by a train": "Trenin çarpması",
  "someone is homeless": "Biri evsiz",
  "someone is kidnapped": "Kaçırılma",
  "someone is misgendered": "Biri yanlış cinsiyetle çağrılıyor",
  "someone is mocked or persecuted for their religion": "Dini yüzünden alay / zulüm",
  "someone is restrained": "Biri bağlanıyor / kısıtlanıyor",
  "someone is terminally ill": "Ölümcül hastalık",
  "someone is watched without knowing": "Biri habersizce izleniyor",
  "someone leaves without saying goodbye": "Biri veda etmeden gidiyor",
  "someone loses their job": "Biri işini kaybediyor",
  "someone performs surgery on themselves": "Kendi kendini ameliyat etme",
  "someone sacrifices themselves": "Biri kendini feda ediyor",
  "someone says the n-word": "Irkçı “n” kelimesi kullanılıyor",
  "someone speaks backwards": "Biri tersten konuşuyor",
  "someone steps on a nail": "Çiviye basma",
  "someone struggles to breathe": "Nefes almakta zorlanma",
  "someone telling the truth is not believed": "Doğruyu söyleyene inanılmıyor",
  "someone wets/soils themselves": "Biri altına kaçırıyor",
  "someone's mouth is covered": "Ağzı kapatılıyor",
  "teeth are damaged": "Dişler zarar görüyor",
  "the abused becomes the abuser": "İstismar edilen istismarcıya dönüşüyor",
  "the abused forgives their abuser": "İstismar edilen istismarcısını affediyor",
  "the black guy dies first": "Siyah karakter ilk ölen oluyor",
  "the fourth wall is broken": "Dördüncü duvar yıkılıyor",
  "the r-slur is used": "Engelliliği aşağılayan “r” kelimesi kullanılıyor",
  "there are \"man in a dress\" jokes": "“Elbiseli erkek” şakaları",
  "there are \"emo\" jokes": "“Emo” şakaları",
  "there are 9/11 depictions": "11 Eylül görüntüleri",
  "there are nazis or swastikas": "Nazi / gamalı haç",
  "there are adoption or foster care themes": "Evlat edinme / koruyucu aile teması",
  "there are bugs": "Böcekler",
  "there are cockroaches": "Hamamböcekleri",
  "there are glitches or technology errors": "Görüntü / teknoloji arızaları",
  "there are homophobic slurs": "Homofobik hakaretler",
  "there are rats or mice": "Fareler",
  "there are razors": "Ustura / jilet",
  "there are repetitive sounds": "Tekrarlayan sesler",
  "there are sharks": "Köpekbalıkları",
  "there are sirens or alarms": "Siren / alarm sesleri",
  "there are snakes": "Yılanlar",
  "there are spiders": "Örümcekler",
  "there are transphobic slurs": "Transfobik hakaretler",
  "there is a baby or unborn child": "Bebek / doğmamış çocuk",
  "there is a tsunami": "Tsunami",
  "there is copaganda": "Polis propagandası",
  "there's aba therapy": "ABA terapisi",
  "there's achilles tendon injury": "Aşil tendonu sakatlığı",
  "there's aphobia": "Aseksüellere karşı önyargı",
  "there's covid-19": "COVID-19",
  "there's islamophobia": "İslamofobi",
  "there's a breakup or divorce": "Ayrılık / boşanma",
  "there's a countdown or time pressure": "Geri sayım / zaman baskısı",
  "there's a cult": "Tarikat",
  "there's a dentist scene": "Diş hekimi sahnesi",
  "there's a funeral or cemetery scene": "Cenaze / mezarlık sahnesi",
  "there's a hospital scene": "Hastane sahnesi",
  "there's a large age gap": "Büyük yaş farkı olan ilişki",
  "there's a mental institution scene": "Akıl hastanesi sahnesi",
  "there's a scene with extreme heights": "Yüksekte tehlikeli sahne",
  "there's ableist language or behavior": "Engelliliği aşağılayan dil / davranış",
  "there's abusive parents": "İstismarcı ebeveynler",
  "there's addiction stigma": "Bağımlılık damgalanıyor",
  "there's an alligator or crocodile": "Timsah",
  "there's an apocalypse or end of the world": "Kıyamet / dünyanın sonu",
  "there's animal fighting": "Hayvan dövüşü",
  "there's anti-indigenous racism": "Yerlilere yönelik ırkçılık",
  "there's anti-abortion themes": "Kürtaj karşıtı temalar",
  "there's bedbugs": "Tahtakuruları",
  "there's biphobia or bi erasure": "Biseksüellere karşı önyargı",
  "there's bisexual cheating": "Biseksüel karakter aldatıyor (klişe)",
  "there's blackface": "Blackface (siyah yüz boyama)",
  "there's body dysmorphia": "Beden algısı bozukluğu",
  "there's body dysphoria": "Beden disforisi",
  "there's childbirth": "Doğum sahnesi",
  "there's climate change": "İklim değişikliği",
  "there's conversion therapy": "Dönüştürme terapisi",
  "there's cultural appropriation": "Kültürel sahiplenme",
  "there's deadnaming or birthnaming": "Eski adıyla çağırma (deadnaming)",
  "there's demons or hell": "Şeytanlar / cehennem",
  "there's dissociation, depersonalization, or derealization": "Dissosiyasyon / gerçekdışılık hissi",
  "there's elder abuse": "Yaşlı istismarı",
  "there's emotional or verbal abuse": "Duygusal / sözlü istismar",
  "there's environmental destruction": "Çevre tahribatı",
  "there's facial distortion": "Yüz deformasyonu",
  "there's farting": "Osuruk şakaları",
  "there's fat jokes": "Kilo üzerinden şakalar",
  "there's fat suits": "Dolgu kostüm (kilolu gösterme)",
  "there's gender essentialism": "Cinsiyetçi kalıp yargılar",
  "there's genital trauma/mutilation": "Cinsel organ yaralanması",
  "there's human trafficking": "İnsan ticareti",
  "there's incarceration": "Hapis / tutukluluk",
  "there's involuntary medical treatment": "İstem dışı tıbbi müdahale",
  "there's menstruation": "Adet dönemi",
  "there's misophonia": "Rahatsız edici yeme/nefes sesleri (misofoni)",
  "there's police brutality": "Polis şiddeti",
  "there's prejudice against children or teens": "Çocuk / gençlere yönelik önyargı",
  "there's queerbaiting": "Queerbaiting",
  "there's religious abuse": "Dini istismar",
  "there's secondhand embarrassment": "Utandırıcı (cringe) sahneler",
  "there's shaving/cutting": "Tıraş / kesme",
  "there's slavery": "Kölelik",
  "there's spitting": "Tükürme",
  "there's surgery or a medical procedure": "Ameliyat / tıbbi işlem",
  "there's underwater scenes": "Su altı sahneleri",
  "there's natural bodies of water": "Göl / deniz gibi doğal su kütleleri",
  "trypophobic content is shown": "Delik korkusu (trypophobia) görüntüleri",
  "women are portrayed as incompetent": "Kadınlar beceriksiz gösteriliyor",
};
